/// Flutter icons CloudIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CloudIcon
///      fonts:
///       - asset: fonts/CloudIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CloudIcon {
  CloudIcon._();

  static const _kFontFam = 'CloudIcon';
  static const _kFontPkg = null;

  static const IconData ic_cloud = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
