/// Flutter icons HexagonIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HexagonIcons
///      fonts:
///       - asset: fonts/HexagonIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HexagonIcons {
  HexagonIcons._();

  static const _kFontFam = 'HexagonIcons';

  static const IconData ic_brain = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData ic_body = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData ic_social = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData ic_spirit = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData ic_nature = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData ic_emotions = IconData(0xe805, fontFamily: _kFontFam);
}
