/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BottomNavBarIcon {
  BottomNavBarIcon._();

  static const _kFontFam = 'BottomNavBarIcon';

  static const IconData ic_find_gym = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData ic_find_gym_filled = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData ic_profile_filled = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData ic_profile = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData ic_programs_filled = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData ic_programs = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData ic_progress_filled = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData ic_progress = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData ic_workouts_filled = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData ic_workouts = IconData(0xe809, fontFamily: _kFontFam);
}
