/// Flutter icons OnboardingIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OnboardingIcons
///      fonts:
///       - asset: fonts/OnboardingIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class OnboardingIcons {
  OnboardingIcons._();

  static const _kFontFam = 'OnboardingIcons';
  static const _kFontPkg = null;

  static const IconData onboarding_arrow_right = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData onboarding_arrow_left = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
