/// Flutter icons ProgramInfoIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ProgramInfoIcons
///      fonts:
///       - asset: fonts/ProgramInfoIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ProgramInfoIcons {
  ProgramInfoIcons._();

  static const _kFontFam = 'ProgramInfoIcons';
  static const _kFontPkg = null;

  static const IconData workouts_filled = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_filled = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData progress = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumpbell = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
