/// Flutter icons ProgrammsIcon2
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ProgrammsIcon2
///      fonts:
///       - asset: fonts/ProgrammsIcon2.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ProgrammsIcon2 {
  ProgrammsIcon2._();

  static const _kFontFam = 'ProgrammsIcon2';
  static const String? _kFontPkg = null;

  static const IconData dumpbell = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
