/// Flutter icons Social_icons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Social_icons
///      fonts:
///       - asset: fonts/Social_icons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class SocialIcons {
  SocialIcons._();

  static const _kFontFam = 'Social_icons';
  static const _kFontPkg = null;

  static const IconData apple_logo =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_logo =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_logo =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
