/// Flutter icons Soun
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Soun
///      fonts:
///       - asset: fonts/Soun.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SoundIcons {
  SoundIcons._();

  static const _kFontFam = 'Sound';
  static const _kFontPkg = null;

  static const IconData music_sign = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_off = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_up = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
